# Generated by Django 3.2.19 on 2023-05-17 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(help_text='Список авторов', max_length=2048)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=256)),
                ('book_title', models.CharField(blank=True, max_length=256)),
                ('publisher', models.CharField(blank=True, max_length=256)),
                ('institution', models.CharField(blank=True, max_length=256)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('keywords', models.CharField(blank=True, help_text='List of keywords separated by commas.', max_length=256)),
                ('url', models.URLField(blank=True, help_text='Link to PDF or journal page.', verbose_name='URL')),
                ('code', models.URLField(blank=True, help_text='Link to page with code.')),
                ('doi', models.CharField(blank=True, max_length=128, verbose_name='DOI')),
                ('abstract', models.TextField(blank=True)),
                ('isbn', models.CharField(blank=True, help_text='Только для книг.', max_length=32, verbose_name='ISBN')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
