# Generated by Django 3.2.19 on 2023-05-25 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publication.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ISSN', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, help_text='Публикация доступна всем')),
                ('date_posted', models.DateTimeField(auto_now_add=True, help_text='Дата публикации на этом сайте')),
                ('file_path', models.FileField(blank=True, null=True, upload_to=publication.models.user_directory_path, verbose_name='PDF')),
                ('publication_type', models.CharField(choices=[('choose', 'Выберите тип'), ('webpage', 'Веб-страница (Электронный ресурс удаленного доступа)'), ('book', 'Книга (Book)'), ('thesis', 'Диссертация и автореферат диссертации (Thesis)'), ('chapter', 'Раздел книги (BookSection)'), ('paper-conference', 'Статья из сборника (Документ конференции) (Conference Paper)'), ('article-newspaper', 'Газетная статья (Newspaper Article)'), ('entry-encyclopedia', 'Статья из энциклопедии (Encyclopedia Article)'), ('article-journal', 'Статья из периодики (Journal Article)'), ('software', 'Электронный ресурс локального доступа (Компьютерная программа) (Computer Program)')], default='choose', max_length=200, verbose_name='Тип')),
                ('citation_key', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('archive', models.CharField(blank=True, max_length=100)),
                ('archive_location', models.CharField(blank=True, max_length=100)),
                ('call_number', models.CharField(blank=True, max_length=100)),
                ('collection_number', models.CharField(blank=True, max_length=100)),
                ('collection_title', models.CharField(blank=True, max_length=100)),
                ('container_title', models.CharField(blank=True, max_length=100)),
                ('edition', models.CharField(blank=True, help_text='Издание (полная строка, например, «1-е, стереотипное»)', max_length=50)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('issue', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_volumes', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.CharField(blank=True, max_length=10)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('title_short', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('volume', models.IntegerField(blank=True, help_text='Том журнала или книги', null=True)),
                ('note', models.CharField(blank=True, help_text='Любые заметки', max_length=256)),
                ('ISBN', models.CharField(blank=True, help_text='Только для книг', max_length=20)),
                ('URL', models.URLField(blank=True, help_text='Ссылка на оригинальную публикацию')),
                ('DOI', models.CharField(blank=True, max_length=128, verbose_name='DOI')),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_publications', to='publication.contributor')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
                ('coauthor', models.ManyToManyField(blank=True, related_name='coauthor_publications', to='publication.Contributor')),
                ('collectioneditor', models.ManyToManyField(blank=True, related_name='collectioneditor_publications', to='publication.Contributor')),
                ('editor', models.ManyToManyField(blank=True, related_name='editor_publications', to='publication.Contributor')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.event')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.journal')),
                ('keyword', taggit.managers.TaggableManager(blank=True, help_text='Ключевые слова (записываются через запятую)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.publisher')),
                ('reviewedauthor', models.ManyToManyField(blank=True, related_name='reviewedauthor_publications', to='publication.Contributor')),
                ('translator', models.ManyToManyField(blank=True, related_name='translator_publications', to='publication.Contributor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
