# Generated by Django 3.2.19 on 2023-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='public',
            field=models.BooleanField(default=True, help_text='Публикация доступна всем'),
        ),
    ]
