# Generated by Django 3.2.19 on 2023-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_journal_issn'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='gost2018',
            field=models.TextField(blank=True, null=True),
        ),
    ]
