# Generated by Django 3.2.19 on 2023-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='PDF'),
        ),
    ]
