# Generated by Django 3.2.19 on 2023-06-01 02:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('publication', '0003_publication_gost2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='gost2008',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_publications', to='publication.contributor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.event', verbose_name='Конференция'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.journal', verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='keyword',
            field=taggit.managers.TaggableManager(blank=True, help_text='Ключевые слова (записываются через запятую)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ключевые словаf'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('choose', 'Выберите тип'), ('webpage', 'Веб-страница (Электронный ресурс удаленного доступа)'), ('book', 'Книга (Book)'), ('thesis', 'Диссертация и автореферат диссертации (Thesis)'), ('chapter', 'Раздел книги (BookSection)'), ('paper-conference', 'Статья из сборника (Документ конференции) (Conference Paper)'), ('article-journal', 'Статья из периодики (Journal Article)')], default='choose', max_length=200, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заглавие'),
        ),
    ]
