# Generated by Django 3.2.19 on 2023-05-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_alter_publication_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, help_text='Список авторов', max_length=2048),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
