# Generated by Django 3.2.19 on 2023-05-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20230517_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bibtex',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
