# Generated by Django 3.2.19 on 2023-05-19 15:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('publication', '0011_auto_20230518_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_rus', models.CharField(blank=True, help_text='Имя', max_length=100)),
                ('family_rus', models.CharField(blank=True, help_text='Фамилия', max_length=100)),
                ('given_eng', models.CharField(blank=True, help_text='Имя', max_length=100)),
                ('family_eng', models.CharField(blank=True, help_text='Фамилия', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(blank=True, max_length=100)),
                ('name_eng', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(blank=True, max_length=256)),
                ('name_eng', models.CharField(blank=True, max_length=256)),
                ('address_rus', models.CharField(blank=True, max_length=100)),
                ('address_eng', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='code',
        ),
        migrations.AddField(
            model_name='publication',
            name='booktitle',
            field=models.CharField(blank=True, help_text='Наименование книги, содержащей данную работу', max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='chapter',
            field=models.CharField(blank=True, help_text='Номер главы', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='crossref',
            field=models.CharField(blank=True, help_text='Ключ кросс-ссылки (позволяет использовать другую библио-запись в качестве названия, например, сборника трудов)', max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='edition',
            field=models.CharField(blank=True, help_text='Издание (полная строка, например, «1-е, стереотипное»)', max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='howpublished',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='id_bibtex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='key',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='organization',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='school',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='series',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, help_text='Аннотация для библиографической записи', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='bibtex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата публикации на этом сайте'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, help_text='Только для книг', max_length=32, verbose_name='ISBN'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.AlterField(
            model_name='publication',
            name='note',
            field=models.CharField(blank=True, help_text='Любые заметки', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(blank=True, help_text='Номер журнала', null=True),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Ключевые слова (записываются через запятую)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, help_text='Тип отчёта, например «Заметки исследователя»', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, help_text='Ссылка на оригинальную публикацию', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(blank=True, help_text='Том журнала или книги', null=True),
        ),
        migrations.CreateModel(
            name='PublicationContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Author', 'Author'), ('Co-Author', 'Co Author'), ('Editor', 'Editor')], max_length=200, verbose_name='Роль')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.contributor')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(blank=True, through='publication.PublicationContributor', to='publication.Contributor'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(blank=True, help_text='Тип публикации. Например: article', null=True, on_delete=django.db.models.deletion.PROTECT, to='publication.publicationtype'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ManyToManyField(blank=True, to='publication.Journal'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='publication.Publisher'),
        ),
    ]
