# Generated by Django 3.2.19 on 2023-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_auto_20230519_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('article', 'Article (Статья из журнала)'), ('book', 'Book (Книга)'), ('booklet', 'Booklet (Печатная работа, которая не содержит имя издателя)'), ('inbook', 'Inbook (Часть книги)'), ('incollection', 'Incollection (Часть книги, имеющая собственное название)'), ('inproceedings', 'Inproceedings (Труд конференции)'), ('manual', 'Manual (Техническая документация)'), ('mastersthesis', 'Mastersthesis (Магистерская диссертация)'), ('misc', 'Misc (Если другие типы не подходят)'), ('phdthesis', 'Phdthesis (Кандидатская диссертация)'), ('proceedings', 'Proceedings (Сборник трудов конференции)'), ('techreport', 'Techreport (Отчет)'), ('unpublished', 'Unpublished (Не опубликовано)')], default='article', max_length=200, verbose_name='Тип'),
        ),
    ]
