# Generated by Django 3.2.19 on 2023-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0015_alter_publication_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True),
        ),
    ]
