# Generated by Django 3.2.19 on 2023-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0016_alter_publication_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='doi',
            new_name='DOI',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='id_bibtex',
            new_name='citation_key',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='tags',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pages',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='crossref',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='key',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='school',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='series',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url',
        ),
        migrations.AddField(
            model_name='publication',
            name='ISBN',
            field=models.CharField(blank=True, help_text='Только для книг', max_length=32),
        ),
        migrations.AddField(
            model_name='publication',
            name='ISSN',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='publication',
            name='URL',
            field=models.URLField(blank=True, help_text='Ссылка на оригинальную публикацию'),
        ),
        migrations.AddField(
            model_name='publication',
            name='annote',
            field=models.TextField(blank=True, help_text='Аннотация для библиографической записи', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='authority',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='issued',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
