# Generated by Django 3.2.19 on 2023-05-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0017_auto_20230519_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='family_rus',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='given_rus',
            new_name='given',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='name_eng',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='address_eng',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='name_eng',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='family_eng',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='given_eng',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='name_rus',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='address_rus',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='name_rus',
        ),
    ]
