# Generated by Django 3.2.19 on 2023-05-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0019_auto_20230523_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='editor',
            field=models.ManyToManyField(blank=True, to='publication.Editor'),
        ),
    ]
