# Generated by Django 3.2.19 on 2023-05-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0020_alter_publication_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.journal'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publisher',
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.publisher'),
        ),
    ]
