# Generated by Django 3.2.19 on 2023-05-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0021_auto_20230524_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='ISSN',
        ),
        migrations.AddField(
            model_name='journal',
            name='ISSN',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
